export const entityPatterns: Record<string, RegExp> = {
  main_battery_level: /sensor\.(.*)_main_battery_level/,
  battery_level: /sensor\.(.*)_battery_level/,
  total_in_power: /sensor\.(.*)_total_in_power/,
  total_out_power: /sensor\.(.*)_total_out_power/,
  ac_in_power: /sensor\.(.*)_ac_in_power/,
  ac_out_power: /sensor\.(.*)_ac_out_power/,
  ac_in_volts: /sensor\.(.*)_ac_in_volts/,
  ac_out_volts: /sensor\.(.*)_ac_out_volts/,
  charge_remaining_time: /sensor\.(.*)_charge_remaining_time/,
  discharge_remaining_time: /sensor\.(.*)_discharge_remaining_time/,
  inv_out_temperature: /sensor\.(.*)_inv_out_temperature/,
  cycles: /sensor\.(.*)_cycles/,
  battery_temperature: /sensor\.(.*)_battery_temperature/,
  status: /sensor\.(.*)_status/,
  ac_enabled: /switch\.(.*)_ac_enabled/,
  x_boost_enabled: /switch\.(.*)_x_boost_enabled/,
  dc_enabled: /switch\.(.*)_dc_12v_enabled/,
  ac_charging_power: /number\.(.*)_ac_charging_power/,
  max_charge_level: /number\.(.*)_max_charge_level/,
  min_discharge_level: /number\.(.*)_min_discharge_level/,
  battery_charging_state: /sensor\.(.*)_battery_charging_state/,
  type_c_in_power: /sensor\.(.*)_type_c_in_power/,
  type_c_out_power: /sensor\.(.*)_type_c_out_power/,
  solar_in_power: /sensor\.(.*)_solar_in_power/,
  dc_out_power: /sensor\.(.*)_dc_out_power/,
  usb_out_power: /sensor\.(.*)_usb_out_power/,
  remaining_time: /sensor\.(.*)_remaining_time/,
  dc_12v_charge_current: /sensor\.(.*)_dc_12v_charge_current/,
  solar1_in_power: /sensor\.(.*)_solar_in_power/,
  solar2_in_power: /sensor\.(.*)_solar_2_in_power/,
  solar1_in_volts: /sensor\.(.*)_solar_in_volts/,
  solar2_in_volts: /sensor\.(.*)_solar_2_in_volts/,
  solar1_in_amps: /sensor\.(.*)_solar_in_amps/,
  solar2_in_amps: /sensor\.(.*)_solar_2_in_amps/,
  type_c1_out_power: /sensor\.(.*)_type_c_1_out_power/,
  type_c2_out_power: /sensor\.(.*)_type_c_2_out_power/,
  usb1_out_power: /sensor\.(.*)_usb_1_out_power/,
  usb2_out_power: /sensor\.(.*)_usb_2_out_power/,
  usb_qc1_out_power: /sensor\.(.*)_usb_qc_1_out_power/,
  usb_qc2_out_power: /sensor\.(.*)_usb_qc_2_out_power/,
  solar_in_energy: /sensor\.(.*)_solar_in_energy/,
  battery_charge_energy_from_ac: /sensor\.(.*)_battery_charge_energy_from_ac/,
  battery_charge_energy_from_dc: /sensor\.(.*)_battery_charge_energy_from_dc/,
  battery_discharge_energy_to_ac: /sensor\.(.*)_battery_discharge_energy_to_ac/,
  battery_discharge_energy_to_dc: /sensor\.(.*)_battery_discharge_energy_to_dc/,
  usb_enabled: /switch\.(.*)_usb_enabled/,
  ac_always_on: /switch\.(.*)_ac_always_on/,
};

export class EntityPattern {
  public getRegex(pattern: keyof typeof entityPatterns): RegExp {
    return entityPatterns[pattern];
  }
}
